version: "3.3"

services:
  app:
    container_name: app
    env_file: .env
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    restart: on-failure:5
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mongo
    command: >
      sh -c "python init_pg_db.py && python init_mongo_db.py && uvicorn main:app --host 0.0.0.0 --port 8000"
    volumes:
      - ..:/workspace

  db:
    container_name: db
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: profi_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    container_name: mongo
    # image: mongo:5.0
    image: mongo:6-jammy
    restart: on-failure:3
    env_file: [.env-mongo, .env]
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: pass
    #   MONGO_INITDB_DATABASE: mongo_profi_db
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      # - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    ports:
      - "27017:27017"
    # healthcheck:
    #   test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet

volumes:
  postgres_data:
  mongo_data:
