version: "3.3"

services:
  app:
    container_name: app
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: >
      sh -c "python init_db.py && uvicorn main:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/workspace

  db:
    container_name: db
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: profi_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
