version: "3.3"

services:
  app:
    container_name: app
    env_file: .env
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    restart: on-failure:5
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mongo
    command: >
      sh -c "python init_pg_db.py && python load_mocks.py && uvicorn main:app --host 0.0.0.0 --port 8000"
    volumes:
      - ..:/workspace

  db:
    container_name: db
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: profi_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    container_name: mongo
    image: mongo:6-jammy
    # image: mongo:5.0
    restart: on-failure:3
    env_file: [.env-mongo, .env]
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      # - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    ports:
      - "27017:27017"

volumes:
  postgres_data:
  mongo_data:
